Task3
eds832/react-js pull request #6
Opened 2023-09-21 15:08 UTC by eds832

2023-09-22 11:34 UTC, Lultik requested changes

2023-09-22 11:34 UTC, Lultik commented on src/components/MovieTile/MovieTile.tsx
> +			</figcaption>
please create separate component for each subcomponent to get possibility to reuse them

2023-09-22 11:34 UTC, Lultik commented on src/components/MovieTile/MovieTitle.css
> +}
please add empty line at the end - it is a good practice in JS and CSS 😄

2023-09-22 11:34 UTC, Lultik commented on src/components/MovieTile/__tests__/movieTitle.test.tsx
> +
1. your test must be atomic (one test for one case)
2. if you create separate components for all subcomponents and create tests for them, you don't need to create test that check behaviour of each sub-component here.

2023-09-22 11:34 UTC, Lultik commented on src/components/SortControl/SortControl.tsx
> +			</select>
you can use jsx feature:
```jsx
const options = ['RELEASE DATE', 'TITLE'];
...
<select>
  {options.map((labelName) => <Option {...someProps}>{labelName}</Option>)}
</select>
```
And please move option to separate component

2023-09-22 11:34 UTC, Lultik commented on src/components/SortControl/__tests__/sortControl.test.tsx
> +	});
this action is redundant here

2023-09-22 11:34 UTC, Lultik commented on src/constants.ts
> +];
Great!

2023-09-22 11:34 UTC, Lultik commented on src/store/movies/types.ts
> +export type MovieType = {
looks like interface

2023-09-22 11:34 UTC, Lultik commented on src/store/movies/types.ts
> +	genresList?: string[];
you know all genres and can create enum with them and define this param as enum

2023-09-22 11:56 UTC, Lultik commented on src/components/MovieTile/MovieTile.tsx
> +					<p data-testid='movie-title-release-year'>{releaseYear}</p>
```jsx
<Typography weight={300} size={24}>{releaseYear}<Typography>
<Typography type={TypographyType.Title}>{releaseYear}<Typography>
```

```jsx
const Typography = ({type, children}: {children: ReactNode}) => {
  return <p className={type}>{children}</p>
}
```
```css
.title {
  weight: 300;
  font-size: 40px;
}
```

2023-09-22 12:32 UTC, Lultik commented on src/components/MovieTile/MovieTile.tsx
> +					<p data-testid='movie-title-release-year'>{releaseYear}</p>
https://ant.design/components/typography#api
https://mui.com/material-ui/api/typography/

2023-10-01 16:38 UTC, Lultik requested changes

2023-10-01 16:38 UTC, Lultik commented on src/components/Typography/Typography.css
> +}
Please use only text css props in generic Typography component.

2023-10-01 16:38 UTC, Lultik commented on src/App.tsx
> +const randomGenerator = () => Math.floor(Math.random() * genres.length);
just create mock list of films in json file and use it

2023-10-01 16:38 UTC, Lultik commented on src/components/Button/Button.tsx
> +	type,
add default value that allows you to avoid ternary operator on 21th line

2023-10-01 16:38 UTC, Lultik commented on src/App.tsx
> +	const [name, setMovie] = useState(null);
please follow useState rules: use or `[name, setName]` or `[movie, setMovie]`.

2023-10-01 16:38 UTC, Lultik commented on src/App.tsx
> +			setMovie(clickedMovieName);
you can set whole movie object to this state and then pass it to Describe component.

2023-10-01 16:38 UTC, Lultik commented on src/components/Input/Input.tsx
> +		target: { value: React.SetStateAction<string> };
I guess type of `value` should be `string` instead of `SetStateAction`

2023-10-01 16:38 UTC, Lultik commented on src/components/Input/Input.tsx
> +	type,
use default value

2023-10-01 16:38 UTC, Lultik commented on src/components/Input/Input.tsx
> +				size={size ? size : 50}
see as above

2023-10-01 16:38 UTC, Lultik commented on src/components/MovieDetails/MovieDetails.tsx
> +				/>
`children` is a component inside this component:
```suggestion
				<Button
					buttonClass='go-to-all-movies-button'
					dataTestid='go-to-all-movies-button'
					onClick={() => onMovieClick(null)}
				>⚲</Button>
```

2023-10-01 16:38 UTC, Lultik commented on src/components/MovieDetails/MovieDetails.tsx
> +						)}
Your Typography component shouldn't depend on content: you should pass type of Typography and conten
`<Typography type="TypographyTypes.MOVIE_DETAILS_RATING">9</Typography>`

2023-10-01 16:38 UTC, Lultik commented on src/components/Typography/Typography.tsx
> +	MOVIE_COUNTER = 'movie-counter',
Are you sure that you have so many different Typography types? Please remember that this component should manage only text styles

2023-10-01 16:38 UTC, Lultik commented on src/store/movies/types.ts
move this file from `store` to `interfaces` of `types` folder

2023-10-01 16:38 UTC, Lultik commented on src/helpers/getMovieDuration.ts
you can remove this file if you create mock file with movies

2023-10-01 16:38 UTC, Lultik commented on src/stories/Counter.stories.tsx
please put every story to folder with appropriate component

2023-10-01 17:01 UTC, Lultik requested changes

2023-10-01 17:01 UTC, Lultik commented on src/components/Option/Option.tsx
> +			{convertValueToTextContent(value)}
what is the reason to do it? You will pass only strings in this component. Just use Typography here (or not). You also don't need `convertCamelCaseToHyphen` and `convertValueToTextContent ` functions.

2023-10-01 17:01 UTC, Lultik commented on src/components/SortControl/SortControl.tsx
> +				value={initialValue}
use `setState` to manage input value

2023-10-01 17:01 UTC, Lultik commented on src/components/SortControl/SortControl.tsx
> +				))}
👍

2023-10-01 17:01 UTC, Lultik commented on src/components/SortControl/SortControl.tsx
> +const options = ['releaseDate', 'title'];
What is the reason to use camel case options? I guess you can use readable strings here

2023-10-01 19:41 UTC, eds832 commented on src/helpers/getMovieDuration.ts
I've looked at https://github.com/VarvaraZadnepriak/MoviesAPI.ReactJS and found out that it uses: "runtime": 128 - duration in an integer number.

2023-10-05 11:11 UTC, merged